name: Django Testing and Linting

on:
  push:
    branches:
      - '*'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Linting Dependencies
      run: |
        pip install flake8 isort

    - name: Run Flake8
      run: flake8 .

    - name: Run isort
      run: isort .

  test:
    runs-on: ubuntu-latest

    env:
      DB_HOST: "localhost"
      SECRET_KEY: "django-insecure-dad&3i!l(cyap0d+(9$l6kvnvgyt&n%c!7ewtlhi)7vcv5slbw"
      DEBUG: "True"

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install PostgreSQL and Database Setup
      run: |
        sudo apt-get update
        sudo apt-get install -y postgresql postgresql-contrib libpq-dev python3-psycopg2
        sudo service postgresql start
        sudo -u postgres psql -c "DROP DATABASE IF EXISTS appdb;"
        sudo -u postgres psql -c "DROP USER IF EXISTS umair;"
        sudo -u postgres psql -c "CREATE USER umair WITH PASSWORD 'umair' CREATEDB;"
        sudo -u postgres psql -c "CREATE DATABASE appdb OWNER umair;"

    - name: Install Testing Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Ensure all dependencies are installed

    - name: Run Django Tests
      run: python3 manage.py test
